### ISSUE TITLE
First Time installing homebrew

### ISSUE THREAD

**Issue by eyadsibai** [zhaofengli/nix-homebrew#32] opened 2024-07-31 10:50 UTC
I am trying to use nix-homebrew on a fresh machine.

getting the following error:

`fatal: could not create work tree dir '/opt/homebrew/Library/Taps/homebrew/homebrew-bundle': Permission denied
`

**Comment by eyadsibai** [comment] 2024-08-01 15:19
do I have to run 'sudo darwin-rebuild' ?

**Comment by Smona** [comment] 2024-08-06 23:52
Looks like this might be a duplicate of #9? Does [this fix](https://github.com/zhaofengli/nix-homebrew/issues/9#issuecomment-1774684583) work for you?

**Comment by dezren39** [comment] 2024-10-22 23:57
yeah that fixes it.

**Closed** 2024-11-12 18:09 UTC
